version: '3'

services:

  lucinda:
    image:  rgwch/lucinda-server:2.1.4
    volumes: 
      - lucinda_home:/var/lucinda/home
      - /path/to/documents:/var/lucinda/docs
    ports:
      - 2016:2016
    restart: always 

volumes:

    lucinda_home:
