openapi: 3.0.2
info:
  title: Lucinda server
  version: "3.0"

paths:
  /lucinda/3.0/ping:
    get:
      responses:
        200:
          description: The server is alive
          content:
            text/plain:
              schema:
                type: string
  /lucinda/3.0/get/{id}:
    description: retrieve the document with the given id
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string

      responses:
        200:
          description: The requested document in binary form
          content:
            application/octet-stream:
              schema:
                type: string
                format: byte
        404:
          description: The requested document was not found
                  
  /lucinda/3.0/query/{expression}:
    description: Query the database with a lucene query expression
    get:
      parameters:
        - name: querystring
          in: path
          required: true
          schema: 
            type: string
      responses:

  /createJob:
    post:
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: array
      responses:
        202:
          description: Lucinda filed the document for import
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobid:
                    type: string
  /fetch/{jobid}:
    get:
      responses:
        200:
          description: The Job is finished. Result is in the body
          content:
            application/octet-stream:
              schema:
                type: array
        204:
          description: The Job is not yet finished. Try again later
        404:
          description: No job wih given jobid exists
